include_directories(
        ../phycoub/phycoubs
        ../phycoub/lifetimecontrollers
        ../phycoub/phyobjects
        ../phycoub/phyobjects/particlefigurematrix
        ../phycoub/phyobjects/intercommunications
        ../phycoub/phyobjects/fieldcreators
        ../phycoub/particlesources
        ../phycoub/borderfieldconditions
        ../phycoub/calculationmodels
        ../phycoub/shapes
        ../phycoub/borderevents
        ../phycoub/borderconditions
        ../phycoub/common
        ../phycoub/interworkingfunctions
        ../phycoub/phymeasurement
        ../phycoub/errors
        ../phycoub/mathematic
        ../phycoub/fieldfunctions
        ../phycoub/particle
        ../phycoub/logging
)

include_directories(
        ../widgets/particleoptionscontroller
        ../widgets/coubglwidget
        ../widgets/directioncontroller
        ../widgets/directiongl
        ../widgets/common
        ../widgets/scalarcontroller
        ../widgets/homogeneousdirectfieldcontroller
        ../widgets/removeparticle
        ../widgets/viewparticletable
        ../widgets/addparticle
        ../widgets/coubcontroller
)