name: Cross platform compilation & Ctest
on:
  push:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        host: mac
        dir: ${{runner.workspace}}/Qt

    - name: Configure CMake
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DQT_PATH=$Qt5_DIR

    - name: Build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Ctest
      shell: bash
      run: ctest -C $BUILD_TYPE --verbose

  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        shell: bash
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: CTest
        shell: bash
        run: ctest -C $BUILD_TYPE --verbose

  build-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          host: windows
          dir: ${{runner.workspace}}/Qt

      - name: Configure CMake
        shell: bash
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DQT_PATH=$Qt5_DIR

      - name: Build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Ctest
        shell: bash
        run: ctest -C $BUILD_TYPE

  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mymindstorm/setup-emsdk@v13

      - name: Configure CMake
        shell: bash
        run: emcmake cmake .

      - name: Build with Emscripten
        shell: bash
        run: cmake --build . --config $BUILD_TYPE
